# ***Extração dos dados***

In [481]:
import requests

In [482]:
# especificando a versão da API
headers = {'X-GitHub-Api-Version': '2022-11-28'}

In [483]:
r = requests.get('https://api.github.com/versions', headers= headers)

In [484]:
api_base_url = 'https://api.github.com/'
owner = 'amzn'

url_amzn = f'{api_base_url}/users/{owner}/repos'

In [485]:
response = requests.get(url_amzn, headers = headers)

In [486]:
response.status_code

200

In [487]:
len(response.json())

30

Autenticação

In [488]:
acesso_token = os.getenv("GITHUB_TOKEN", "SEU_TOKEN_AQUI")
headers = {
    "Authorization": f"Bearer {acesso_token}",
    "Accept": "application/vnd.github.v3+json"
}

Paginando os repositórios

In [489]:
repos_list = []
for page_num in range (1, 7):
  try:
    url_page = f'{url_amzn}?page={page_num}'
    response = requests.get(url_page, headers = headers)
    repos_list.append(response.json())
  except: repos_list.append(None)

In [490]:
len(repos_list)

6

In [491]:
len(repos_list[0])

30

# ***Transformação dos dados***

Nome dos repositórios

In [492]:
repos_list[0][1]

{'id': 492978607,
 'node_id': 'R_kgDOHWJBrw',
 'name': 'ads-advanced-tools-docs',
 'full_name': 'amzn/ads-advanced-tools-docs',
 'private': False,
 'owner': {'login': 'amzn',
  'id': 8594673,
  'node_id': 'MDEyOk9yZ2FuaXphdGlvbjg1OTQ2NzM=',
  'avatar_url': 'https://avatars.githubusercontent.com/u/8594673?v=4',
  'gravatar_id': '',
  'url': 'https://api.github.com/users/amzn',
  'html_url': 'https://github.com/amzn',
  'followers_url': 'https://api.github.com/users/amzn/followers',
  'following_url': 'https://api.github.com/users/amzn/following{/other_user}',
  'gists_url': 'https://api.github.com/users/amzn/gists{/gist_id}',
  'starred_url': 'https://api.github.com/users/amzn/starred{/owner}{/repo}',
  'subscriptions_url': 'https://api.github.com/users/amzn/subscriptions',
  'organizations_url': 'https://api.github.com/users/amzn/orgs',
  'repos_url': 'https://api.github.com/users/amzn/repos',
  'events_url': 'https://api.github.com/users/amzn/events{/privacy}',
  'received_events_url': 'https://api.github.com/users/amzn/received_events',
  'type': 'Organization',
  'user_view_type': 'public',
  'site_admin': False},
 'html_url': 'https://github.com/amzn/ads-advanced-tools-docs',
 'description': 'Code samples and supplements for the Amazon Ads advanced tools center',
 'fork': False,
 'url': 'https://api.github.com/repos/amzn/ads-advanced-tools-docs',
 'forks_url': 'https://api.github.com/repos/amzn/ads-advanced-tools-docs/forks',
 'keys_url': 'https://api.github.com/repos/amzn/ads-advanced-tools-docs/keys{/key_id}',
 'collaborators_url': 'https://api.github.com/repos/amzn/ads-advanced-tools-docs/collaborators{/collaborator}',
 'teams_url': 'https://api.github.com/repos/amzn/ads-advanced-tools-docs/teams',
 'hooks_url': 'https://api.github.com/repos/amzn/ads-advanced-tools-docs/hooks',
 'issue_events_url': 'https://api.github.com/repos/amzn/ads-advanced-tools-docs/issues/events{/number}',
 'events_url': 'https://api.github.com/repos/amzn/ads-advanced-tools-docs/events',
 'assignees_url': 'https://api.github.com/repos/amzn/ads-advanced-tools-docs/assignees{/user}',
 'branches_url': 'https://api.github.com/repos/amzn/ads-advanced-tools-docs/branches{/branch}',
 'tags_url': 'https://api.github.com/repos/amzn/ads-advanced-tools-docs/tags',
 'blobs_url': 'https://api.github.com/repos/amzn/ads-advanced-tools-docs/git/blobs{/sha}',
 'git_tags_url': 'https://api.github.com/repos/amzn/ads-advanced-tools-docs/git/tags{/sha}',
 'git_refs_url': 'https://api.github.com/repos/amzn/ads-advanced-tools-docs/git/refs{/sha}',
 'trees_url': 'https://api.github.com/repos/amzn/ads-advanced-tools-docs/git/trees{/sha}',
 'statuses_url': 'https://api.github.com/repos/amzn/ads-advanced-tools-docs/statuses/{sha}',
 'languages_url': 'https://api.github.com/repos/amzn/ads-advanced-tools-docs/languages',
 'stargazers_url': 'https://api.github.com/repos/amzn/ads-advanced-tools-docs/stargazers',
 'contributors_url': 'https://api.github.com/repos/amzn/ads-advanced-tools-docs/contributors',
 'subscribers_url': 'https://api.github.com/repos/amzn/ads-advanced-tools-docs/subscribers',
 'subscription_url': 'https://api.github.com/repos/amzn/ads-advanced-tools-docs/subscription',
 'commits_url': 'https://api.github.com/repos/amzn/ads-advanced-tools-docs/commits{/sha}',
 'git_commits_url': 'https://api.github.com/repos/amzn/ads-advanced-tools-docs/git/commits{/sha}',
 'comments_url': 'https://api.github.com/repos/amzn/ads-advanced-tools-docs/comments{/number}',
 'issue_comment_url': 'https://api.github.com/repos/amzn/ads-advanced-tools-docs/issues/comments{/number}',
 'contents_url': 'https://api.github.com/repos/amzn/ads-advanced-tools-docs/contents/{+path}',
 'compare_url': 'https://api.github.com/repos/amzn/ads-advanced-tools-docs/compare/{base}...{head}',
 'merges_url': 'https://api.github.com/repos/amzn/ads-advanced-tools-docs/merges',
 'archive_url': 'https://api.github.com/repos/amzn/ads-advanced-tools-docs/{archive_format}{/ref}',
 'downloads_url': 'https://api.github.com/repos/amzn/ads-advanced-tools-docs/downloads',
 'issues_url': 'https://api.github.com/repos/amzn/ads-advanced-tools-docs/issues{/number}',
 'pulls_url': 'https://api.github.com/repos/amzn/ads-advanced-tools-docs/pulls{/number}',
 'milestones_url': 'https://api.github.com/repos/amzn/ads-advanced-tools-docs/milestones{/number}',
 'notifications_url': 'https://api.github.com/repos/amzn/ads-advanced-tools-docs/notifications{?since,all,participating}',
 'labels_url': 'https://api.github.com/repos/amzn/ads-advanced-tools-docs/labels{/name}',
 'releases_url': 'https://api.github.com/repos/amzn/ads-advanced-tools-docs/releases{/id}',
 'deployments_url': 'https://api.github.com/repos/amzn/ads-advanced-tools-docs/deployments',
 'created_at': '2022-05-16T19:49:03Z',
 'updated_at': '2026-07-18T16:12:55Z',
 'pushed_at': '2026-07-06T23:20:48Z',
 'git_url': 'git://github.com/amzn/ads-advanced-tools-docs.git',
 'ssh_url': 'git@github.com:amzn/ads-advanced-tools-docs.git',
 'clone_url': 'https://github.com/amzn/ads-advanced-tools-docs.git',
 'svn_url': 'https://github.com/amzn/ads-advanced-tools-docs',
 'homepage': 'https://advertising.amazon.com/API/docs/en-us/index',
 'size': 70273,
 'stargazers_count': 159,
 'watchers_count': 159,
 'language': 'Python',
 'has_issues': True,
 'has_projects': False,
 'has_downloads': False,
 'has_wiki': False,
 'has_pages': False,
 'has_discussions': True,
 'forks_count': 52,
 'mirror_url': None,
 'archived': False,
 'disabled': False,
 'open_issues_count': 70,
 'license': {'key': 'mit-0',
  'name': 'MIT No Attribution',
  'spdx_id': 'MIT-0',
  'url': 'https://api.github.com/licenses/mit-0',
  'node_id': 'MDc6TGljZW5zZTQx'},
 'allow_forking': True,
 'is_template': False,
 'web_commit_signoff_required': False,
 'has_pull_requests': True,
 'pull_request_creation_policy': 'all',
 'topics': ['amazon', 'amazon-ads-api', 'amazon-marketing-stream'],
 'visibility': 'public',
 'forks': 52,
 'open_issues': 70,
 'watchers': 159,
 'default_branch': 'main',
 'permissions': {'admin': False,
  'maintain': False,
  'push': False,
  'triage': False,
  'pull': True}}

In [493]:
repos_list[0][1]['name']

'ads-advanced-tools-docs'

In [494]:
repos_name = []

for page_name in repos_list:
  for repo in page_name:
    repos_name.append(repo['name'])

In [495]:
len(repos_name)

167

Linguagem utilizada nos repositórios

In [496]:
repos_list[0][1]

{'id': 492978607,
 'node_id': 'R_kgDOHWJBrw',
 'name': 'ads-advanced-tools-docs',
 'full_name': 'amzn/ads-advanced-tools-docs',
 'private': False,
 'owner': {'login': 'amzn',
  'id': 8594673,
  'node_id': 'MDEyOk9yZ2FuaXphdGlvbjg1OTQ2NzM=',
  'avatar_url': 'https://avatars.githubusercontent.com/u/8594673?v=4',
  'gravatar_id': '',
  'url': 'https://api.github.com/users/amzn',
  'html_url': 'https://github.com/amzn',
  'followers_url': 'https://api.github.com/users/amzn/followers',
  'following_url': 'https://api.github.com/users/amzn/following{/other_user}',
  'gists_url': 'https://api.github.com/users/amzn/gists{/gist_id}',
  'starred_url': 'https://api.github.com/users/amzn/starred{/owner}{/repo}',
  'subscriptions_url': 'https://api.github.com/users/amzn/subscriptions',
  'organizations_url': 'https://api.github.com/users/amzn/orgs',
  'repos_url': 'https://api.github.com/users/amzn/repos',
  'events_url': 'https://api.github.com/users/amzn/events{/privacy}',
  'received_events_url': 'https://api.github.com/users/amzn/received_events',
  'type': 'Organization',
  'user_view_type': 'public',
  'site_admin': False},
 'html_url': 'https://github.com/amzn/ads-advanced-tools-docs',
 'description': 'Code samples and supplements for the Amazon Ads advanced tools center',
 'fork': False,
 'url': 'https://api.github.com/repos/amzn/ads-advanced-tools-docs',
 'forks_url': 'https://api.github.com/repos/amzn/ads-advanced-tools-docs/forks',
 'keys_url': 'https://api.github.com/repos/amzn/ads-advanced-tools-docs/keys{/key_id}',
 'collaborators_url': 'https://api.github.com/repos/amzn/ads-advanced-tools-docs/collaborators{/collaborator}',
 'teams_url': 'https://api.github.com/repos/amzn/ads-advanced-tools-docs/teams',
 'hooks_url': 'https://api.github.com/repos/amzn/ads-advanced-tools-docs/hooks',
 'issue_events_url': 'https://api.github.com/repos/amzn/ads-advanced-tools-docs/issues/events{/number}',
 'events_url': 'https://api.github.com/repos/amzn/ads-advanced-tools-docs/events',
 'assignees_url': 'https://api.github.com/repos/amzn/ads-advanced-tools-docs/assignees{/user}',
 'branches_url': 'https://api.github.com/repos/amzn/ads-advanced-tools-docs/branches{/branch}',
 'tags_url': 'https://api.github.com/repos/amzn/ads-advanced-tools-docs/tags',
 'blobs_url': 'https://api.github.com/repos/amzn/ads-advanced-tools-docs/git/blobs{/sha}',
 'git_tags_url': 'https://api.github.com/repos/amzn/ads-advanced-tools-docs/git/tags{/sha}',
 'git_refs_url': 'https://api.github.com/repos/amzn/ads-advanced-tools-docs/git/refs{/sha}',
 'trees_url': 'https://api.github.com/repos/amzn/ads-advanced-tools-docs/git/trees{/sha}',
 'statuses_url': 'https://api.github.com/repos/amzn/ads-advanced-tools-docs/statuses/{sha}',
 'languages_url': 'https://api.github.com/repos/amzn/ads-advanced-tools-docs/languages',
 'stargazers_url': 'https://api.github.com/repos/amzn/ads-advanced-tools-docs/stargazers',
 'contributors_url': 'https://api.github.com/repos/amzn/ads-advanced-tools-docs/contributors',
 'subscribers_url': 'https://api.github.com/repos/amzn/ads-advanced-tools-docs/subscribers',
 'subscription_url': 'https://api.github.com/repos/amzn/ads-advanced-tools-docs/subscription',
 'commits_url': 'https://api.github.com/repos/amzn/ads-advanced-tools-docs/commits{/sha}',
 'git_commits_url': 'https://api.github.com/repos/amzn/ads-advanced-tools-docs/git/commits{/sha}',
 'comments_url': 'https://api.github.com/repos/amzn/ads-advanced-tools-docs/comments{/number}',
 'issue_comment_url': 'https://api.github.com/repos/amzn/ads-advanced-tools-docs/issues/comments{/number}',
 'contents_url': 'https://api.github.com/repos/amzn/ads-advanced-tools-docs/contents/{+path}',
 'compare_url': 'https://api.github.com/repos/amzn/ads-advanced-tools-docs/compare/{base}...{head}',
 'merges_url': 'https://api.github.com/repos/amzn/ads-advanced-tools-docs/merges',
 'archive_url': 'https://api.github.com/repos/amzn/ads-advanced-tools-docs/{archive_format}{/ref}',
 'downloads_url': 'https://api.github.com/repos/amzn/ads-advanced-tools-docs/downloads',
 'issues_url': 'https://api.github.com/repos/amzn/ads-advanced-tools-docs/issues{/number}',
 'pulls_url': 'https://api.github.com/repos/amzn/ads-advanced-tools-docs/pulls{/number}',
 'milestones_url': 'https://api.github.com/repos/amzn/ads-advanced-tools-docs/milestones{/number}',
 'notifications_url': 'https://api.github.com/repos/amzn/ads-advanced-tools-docs/notifications{?since,all,participating}',
 'labels_url': 'https://api.github.com/repos/amzn/ads-advanced-tools-docs/labels{/name}',
 'releases_url': 'https://api.github.com/repos/amzn/ads-advanced-tools-docs/releases{/id}',
 'deployments_url': 'https://api.github.com/repos/amzn/ads-advanced-tools-docs/deployments',
 'created_at': '2022-05-16T19:49:03Z',
 'updated_at': '2026-07-18T16:12:55Z',
 'pushed_at': '2026-07-06T23:20:48Z',
 'git_url': 'git://github.com/amzn/ads-advanced-tools-docs.git',
 'ssh_url': 'git@github.com:amzn/ads-advanced-tools-docs.git',
 'clone_url': 'https://github.com/amzn/ads-advanced-tools-docs.git',
 'svn_url': 'https://github.com/amzn/ads-advanced-tools-docs',
 'homepage': 'https://advertising.amazon.com/API/docs/en-us/index',
 'size': 70273,
 'stargazers_count': 159,
 'watchers_count': 159,
 'language': 'Python',
 'has_issues': True,
 'has_projects': False,
 'has_downloads': False,
 'has_wiki': False,
 'has_pages': False,
 'has_discussions': True,
 'forks_count': 52,
 'mirror_url': None,
 'archived': False,
 'disabled': False,
 'open_issues_count': 70,
 'license': {'key': 'mit-0',
  'name': 'MIT No Attribution',
  'spdx_id': 'MIT-0',
  'url': 'https://api.github.com/licenses/mit-0',
  'node_id': 'MDc6TGljZW5zZTQx'},
 'allow_forking': True,
 'is_template': False,
 'web_commit_signoff_required': False,
 'has_pull_requests': True,
 'pull_request_creation_policy': 'all',
 'topics': ['amazon', 'amazon-ads-api', 'amazon-marketing-stream'],
 'visibility': 'public',
 'forks': 52,
 'open_issues': 70,
 'watchers': 159,
 'default_branch': 'main',
 'permissions': {'admin': False,
  'maintain': False,
  'push': False,
  'triage': False,
  'pull': True}}

In [497]:
repos_list[0][1]['language']

'Python'

In [498]:
repos_language = []

for page_name in repos_list:
  for repo in page_name:
    repos_language.append(repo['language'])

In [499]:
len(repos_language)

167

Criando um DataFrame com os dados tratados

In [500]:
import pandas as pd

In [501]:
dados_amazon = pd.DataFrame()
dados_amazon['Nome repositório'] = repos_name
dados_amazon['Linguagem do repositório'] = repos_language

In [502]:
dados_amazon

                            Nome repositório Linguagem do repositório
0                                    .github                     None
1                    ads-advanced-tools-docs                   Python
2    ads-pao-amznjs-gtm-server-side-template                   Smarty
3                ads-pao-amznjs-gtm-template                   Smarty
4                                 alexa-coho               JavaScript
..                                       ...                      ...
162                         zeek-plugin-enip                     Zeek
163                     zeek-plugin-profinet                     Zeek
164                       zeek-plugin-s7comm                     Zeek
165                          zeek-plugin-tds                     Zeek
166                           zero-shot-rlhr                   Python

[167 rows x 2 columns]

In [508]:
dados_amazon['Linguagem do repositório'].value_counts()

Linguagem do repositório
Python              54
Java                19
Swift               12
TypeScript          10
JavaScript           9
PHP                  8
C#                   6
Zeek                 5
Kotlin               4
Ruby                 4
Jupyter Notebook     3
C                    3
C++                  2
Smarty               2
Go                   2
PowerShell           1
CSS                  1
Rust                 1
Objective-C          1
Cuda                 1
HTML                 1
Scala                1
Mustache             1
Name: count, dtype: int64

# ***Carregando os dados***

Salvando o DataFrame em CSV

In [503]:
dados_amazon.to_csv('amazon_languages.CSV')

Salvando o arquivo no meu repositório GitHub

In [504]:
import base64

from google.colab import drive
drive.mount('/content/drive')

#Salvando notebook no Google Drive
!cp "/content/PYTHON_ETL_+_API_GITHUB.ipynb" "/content/drive/MyDrive/PYTHON_ETL_+_API_GITHUB.ipynb"

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [505]:
url = "https://api.github.com/repos/owendelsantos/Portfolio_Analista_de_Dados/contents/PYTHON: ETL + API GITHUB.ipynb"

# Lê o notebook salvo no Colab
with open("/content/PYTHON_ETL_+_API_GITHUB.ipynb", "rb") as f:
    conteudo = f.read()

dados = {
    "message": "Criando novo notebook no repositório",
    "content": base64.b64encode(conteudo).decode("utf-8"),
    "branch": "main"
}

response = requests.put(url, json=dados, headers=headers)
print(response.status_code)   # 201 = criado
print(response.json())

201
{'content': {'name': 'PYTHON: ETL + API GITHUB.ipynb', 'path': 'PYTHON: ETL + API GITHUB.ipynb', 'sha': 'a1923dd964b4eabff976bd03602c5439aee7005b', 'size': 43061, 'url': 'https://api.github.com/repos/owendelsantos/Portfolio_Analista_de_Dados/contents/PYTHON:%20ETL%20%2B%20API%20GITHUB.ipynb?ref=main', 'html_url': 'https://github.com/owendelsantos/Portfolio_Analista_de_Dados/blob/main/PYTHON:%20ETL%20%2B%20API%20GITHUB.ipynb', 'git_url': 'https://api.github.com/repos/owendelsantos/Portfolio_Analista_de_Dados/git/blobs/a1923dd964b4eabff976bd03602c5439aee7005b', 'download_url': 'https://raw.githubusercontent.com/owendelsantos/Portfolio_Analista_de_Dados/main/PYTHON: ETL + API GITHUB.ipynb', 'type': 'file', '_links': {'self': 'https://api.github.com/repos/owendelsantos/Portfolio_Analista_de_Dados/contents/PYTHON:%20ETL%20%2B%20API%20GITHUB.ipynb?ref=main', 'git': 'https://api.github.com/repos/owendelsantos/Portfolio_Analista_de_Dados/git/blobs/a1923dd964b4eabff976bd03602c5439aee7005b', 'html': 'https://github.com/owendelsantos/Portfolio_Analista_de_Dados/blob/main/PYTHON:%20ETL%20%2B%20API%20GITHUB.ipynb'}}, 'commit': {'sha': '38812ec1f97f794f6747a4c1d252b1807a6b2116', 'node_id': 'C_kwDORMfluNoAKDM4ODEyZWMxZjk3Zjc5NGY2NzQ3YTRjMWQyNTJiMTgwN2E2YjIxMTY', 'url': 'https://api.github.com/repos/owendelsantos/Portfolio_Analista_de_Dados/git/commits/38812ec1f97f794f6747a4c1d252b1807a6b2116', 'html_url': 'https://github.com/owendelsantos/Portfolio_Analista_de_Dados/commit/38812ec1f97f794f6747a4c1d252b1807a6b2116', 'author': {'name': 'Wendel Santos', 'email': 'wendel.correa97@gmail.com', 'date': '2026-07-23T22:14:18Z'}, 'committer': {'name': 'Wendel Santos', 'email': 'wendel.correa97@gmail.com', 'date': '2026-07-23T22:14:18Z'}, 'tree': {'sha': '86183b65ca33e6bde33c6f53706708109c7f976b', 'url': 'https://api.github.com/repos/owendelsantos/Portfolio_Analista_de_Dados/git/trees/86183b65ca33e6bde33c6f53706708109c7f976b'}, 'message': 'Criando novo notebook no repositório', 'parents': [{'sha': '4f671282244873509c1eabde4928aff00461d962', 'url': 'https://api.github.com/repos/owendelsantos/Portfolio_Analista_de_Dados/git/commits/4f671282244873509c1eabde4928aff00461d962', 'html_url': 'https://github.com/owendelsantos/Portfolio_Analista_de_Dados/commit/4f671282244873509c1eabde4928aff00461d962'}], 'verification': {'verified': False, 'reason': 'unsigned', 'signature': None, 'payload': None, 'verified_at': None}}}